-
  name: 'List documents'
  uriPattern: 'neos/content-api/documents'
  defaults:
    '@package': 'Networkteam.Neos.ContentApi'
    '@controller': 'Documents'
    '@action': 'index'
  httpMethods: ['GET']
  appendExceedingArguments: true
-
  name: 'Render document'
  uriPattern: 'neos/content-api/document'
  defaults:
    '@package': 'Networkteam.Neos.ContentApi'
    '@controller': 'Documents'
    '@action': 'document'
  httpMethods: ['GET']
  appendExceedingArguments: true
-
  name: 'Render node'
  uriPattern: 'neos/content-api/node'
  defaults:
    '@package': 'Networkteam.Neos.ContentApi'
    '@controller': 'Documents'
    '@action': 'node'
  httpMethods: ['GET']
  appendExceedingArguments: true
-
  name: 'Render current site'
  uriPattern: 'neos/content-api/site'
  defaults:
    '@package': 'Networkteam.Neos.ContentApi'
    '@controller': 'Sites'
    '@action': 'current'
  httpMethods: ['GET']
  appendExceedingArguments: true
-
  name: 'Fetch data from query'
  uriPattern: 'neos/content-api/query/{queryName}'
  defaults:
    '@package': 'Networkteam.Neos.ContentApi'
    '@controller': 'Documents'
    '@action': 'query'
  httpMethods: ['GET']
  appendExceedingArguments: true
