-
  name: 'List documents'
  uriPattern: 'content-api/documents'
  defaults:
    '@package': 'Networkteam.Neos.ContentApi'
    '@controller': 'Documents'
    '@action': 'index'
  httpMethods: ['GET']
  appendExceedingArguments: true
-
  name: 'Render document'
  uriPattern: 'content-api/render'
  defaults:
    '@package': 'Networkteam.Neos.ContentApi'
    '@controller': 'Documents'
    '@action': 'show'
  httpMethods: ['GET']
  appendExceedingArguments: true
-
  name: 'Render current site'
  uriPattern: 'content-api/site'
  defaults:
    '@package': 'Networkteam.Neos.ContentApi'
    '@controller': 'Sites'
    '@action': 'current'
  httpMethods: ['GET']
  appendExceedingArguments: true
