Networkteam:
  Neos:
    ContentApi:
      recursiveReferencePropertyDepth: 1
      documentList:
        ignoredNodeTypes:
          - 'Neos.Neos:Shortcut'
      # Enable to check redirects of RedirectsHandler (if package is available) if a node is not found
      checkRedirects: false

Neos:
  Flow:
    mvc:
      routes:
        'Networkteam.Neos.ContentApi':
          position: 'before Neos.Neos'

        'Neos.Neos':
          variables:
            # Do not use an URI suffix
            'defaultUriSuffix': ''

    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Networkteam.Neos.ContentApi:Controllers':
                pattern: 'ControllerObjectName'
                patternOptions:
                  controllerObjectNamePattern: 'Networkteam\Neos\ContentApi\Controller\.*'

  Neos:
    fusion:
      autoInclude:
        'Networkteam.Neos.ContentApi': true

  Fusion:
    defaultContext:
      Neos.Ui.NodeInfo: Neos\Neos\Ui\Fusion\Helper\NodeInfoHelper
