Networkteam:
  Neos:
    ContentApi:
      revalidateUrl: 'http://localhost:3000/api/revalidate'
      revalidateToken: 'a-secret-token'
      recursiveReferencePropertyDepth: 1

Neos:
  Flow:
    mvc:
      routes:
        'Networkteam.Neos.ContentApi':
          position: 'before Neos.Neos'

        'Neos.Neos':
          variables:
            # Do not use an URI suffix
            'defaultUriSuffix': ''

    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Networkteam.Neos.ContentApi:Controllers':
                pattern: 'ControllerObjectName'
                patternOptions:
                  controllerObjectNamePattern: 'Networkteam\Neos\ContentApi\Controller\.*'

  Neos:
    fusion:
      autoInclude:
        'Networkteam.Neos.ContentApi': true

  Fusion:
    defaultContext:
      Neos.Ui.NodeInfo: Neos\Neos\Ui\Fusion\Helper\NodeInfoHelper
